### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by NightRaven1107** [OseSem/battlemetrics#1]
hello. how do i use this?

**Comment by Gnomeslayer** [comment]
Hey there!
I provided a lot of information in the readme as well as some example usages in the example.py file.
If you're still having difficulties you're welcome to directly message me on Discord @Gnomeslayer  I'll be more than happy to walk you through anything you're having trouble with.

**Comment by Gnomeslayer** [comment]
Hey there!
I provided a lot of information in the readme as well as some example usages in the example.py file.
If you're still having difficulties you're welcome to directly message me on Discord @Gnomeslayer  I'll be more than happy to walk you through anything you're having trouble with.
